/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_structure_test_MyJniClass */

#ifndef _Included_com_structure_test_MyJniClass
#define _Included_com_structure_test_MyJniClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_structure_test_MyJniClass
 * Method:    DisplayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_structure_test_MyJniClass_DisplayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
